### ISSUE TITLE
DAY 1.1: Project Setup (2hrs)

### ISSUE THREAD

**Issue by absolutemadla8** [OftenTravel/notification-microservice#1]
## Sprint: Day 1 - Foundation
**Assignee**: Backend Developer  
**Estimate**: 2 hours  
**Priority**: High

### Description
Create the foundational project structure and basic setup for the notification microservice with PostgreSQL integration.

### Tasks
- [ ] Create FastAPI project structure
- [ ] Setup virtual environment and requirements.txt
- [ ] Configure environment variables (.env files)
- [ ] Docker setup with PostgreSQL (Dockerfile + docker-compose.yml)
- [ ] Git repository initialization

### Enhanced Dependencies
```
# Core FastAPI
fastapi==0.104.1
uvicorn==0.24.0
pydantic==2.5.0
pydantic-settings==2.1.0

# HTTP Client
httpx==0.25.2

# Database
sqlalchemy==2.0.23
asyncpg==0.29.0
alembic==1.13.1

# Environment & Config
python-dotenv==1.0.0

# Development & Testing
pytest==7.4.3
pytest-asyncio==0.21.1
pytest-mock==3.12.0

# Logging & Monitoring
structlog==23.2.0
```

### Docker Compose Setup
```yaml
version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  notification-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://notification_user:${POSTGRES_PASSWORD:-dev_password}@postgres:5432/notification_service
      - MSG91_API_KEY=${MSG91_API_KEY}
      - MSG91_SENDER_ID=${MSG91_SENDER_ID}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
```

### Project Structure
```
notification-microservice/
├── app/
│   ├── __init__.py
│   ├── main.py
│   ├── core/
│   │   ├── __init__.py
│   │   ├── config.py
│   │   └── database.py
│   ├── models/
│   │   ├── __init__.py
│   │   ├── notification.py
│   │   └── provider.py
│   ├── providers/
│   │   ├── __init__.py
│   │   ├── base.py
│   │   └── msg91.py
│   ├── repositories/
│   │   ├── __init__.py
│   │   └── notification.py
│   ├── services/
│   │   ├── __init__.py
│   │   └── notification.py
│   └── api/
│       ├── __init__.py
│       └── routes/
├── alembic/
├── tests/
├── docker-compose.yml
├── Dockerfile
├── requirements.txt
├── alembic.ini
└── .env.example
```

### Acceptance Criteria
- [ ] Project structure follows FastAPI best practices
- [ ] PostgreSQL integration configured
- [ ] Environment configuration working
- [ ] Docker containers can be built and run
- [ ] Requirements.txt includes all necessary dependencies
- [ ] Git repository properly initialized with .gitignore
- [ ] Database connectivity working
- [ ] Alembic initialized for migrations
