### ISSUE TITLE
DAY 2.1: Database Setup (2hrs)

### ISSUE THREAD

**Issue by absolutemadla8** [OftenTravel/notification-microservice#4]
## Sprint: Day 2 - Core Service
**Assignee**: Backend Developer  
**Estimate**: 2 hours  
**Priority**: High

### Description
Create database models and repository layer for storing notification data, provider configurations, and delivery status using PostgreSQL.

### Tasks
- [ ] PostgreSQL setup with Docker
- [ ] SQLAlchemy models and Alembic migrations
- [ ] Create notification and provider tables
- [ ] Repository pattern implementation
- [ ] Database connection management with connection pooling

### Enhanced Schema Design
```sql
-- Providers table for dynamic provider management
CREATE TABLE providers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    type VARCHAR(20) NOT NULL, -- 'sms', 'email', 'whatsapp'
    is_active BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 1,
    config JSONB, -- Provider-specific configuration
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Enhanced notifications table
CREATE TABLE notifications (
    id SERIAL PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    recipient VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    subject VARCHAR(500), -- For emails
    status VARCHAR(20) DEFAULT 'pending',
    provider_id INTEGER REFERENCES providers(id),
    metadata JSONB, -- Flexible data (template vars, etc.)
    scheduled_at TIMESTAMP,
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    failed_at TIMESTAMP,
    retry_count INTEGER DEFAULT 0,
    error_message TEXT,
    external_id VARCHAR(255), -- Provider's reference ID
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Delivery attempts for retry tracking
CREATE TABLE delivery_attempts (
    id SERIAL PRIMARY KEY,
    notification_id INTEGER REFERENCES notifications(id),
    provider_id INTEGER REFERENCES providers(id),
    status VARCHAR(20) NOT NULL,
    error_message TEXT,
    attempted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    response_data JSONB -- Full provider response
);

-- Indexes for performance
CREATE INDEX idx_notifications_status ON notifications(status);
CREATE INDEX idx_notifications_recipient ON notifications(recipient);
CREATE INDEX idx_notifications_created_at ON notifications(created_at);
CREATE INDEX idx_notifications_type ON notifications(type);
CREATE INDEX idx_delivery_attempts_notification_id ON delivery_attempts(notification_id);
```

### Docker Compose Addition
```yaml
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notification_user -d notification_service"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
```

### SQLAlchemy Models
- Provider model with JSON config field
- Notification model with comprehensive tracking
- DeliveryAttempt model for retry history
- Proper relationships and constraints

### Acceptance Criteria
- [ ] PostgreSQL running in Docker container
- [ ] SQLAlchemy models created with proper relationships
- [ ] Alembic migrations for schema management
- [ ] Repository classes with async operations
- [ ] Connection pooling configured (asyncpg)
- [ ] Database health checks implemented
- [ ] Indexes created for performance
- [ ] Provider seeding (MSG91 initial setup)
